# Generated by Django 5.0 on 2023-12-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('action_type', models.CharField(default='call', max_length=100)),
                ('strike', models.FloatField()),
                ('premium', models.FloatField()),
                ('n', models.IntegerField(default=100)),
                ('action', models.CharField(default='sell', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
