# Generated by Django 5.0 on 2023-12-31 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0003_alter_strategy_options_rename_name_strategy_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('formula', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('option_type', models.CharField(choices=[('Call', 'Call'), ('Put', 'Put')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='strategy',
            options={},
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='action',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='n',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='pinned',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='strike',
        ),
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='options',
            field=models.ManyToManyField(to='finance_api.option'),
        ),
        migrations.CreateModel(
            name='ProbabilityOfProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_api.financialcalculator')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_api.strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='option',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_api.stock'),
        ),
    ]
