# Generated by Django 5.0 on 2024-01-01 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0004_financialcalculator_option_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probabilityofprofit',
            name='calculation',
        ),
        migrations.RemoveField(
            model_name='option',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='options',
        ),
        migrations.RemoveField(
            model_name='probabilityofprofit',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='compute_expectation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='compute_the_greeks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='country',
            field=models.CharField(default='US', max_length=50),
        ),
        migrations.AddField(
            model_name='strategy',
            name='days2targetdate',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='strategy',
            name='discard_nonbusinessdays',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='distribution',
            field=models.CharField(default='black-scholes', max_length=50),
        ),
        migrations.AddField(
            model_name='strategy',
            name='dividendyield',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='interestrate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='losslimit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='maxstock',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='minstock',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='nmcprices',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='strategy',
            name='optcommission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='profittarg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='stockcommission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='stockprice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='strategy_name',
            field=models.CharField(default='no-name'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='targetdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='use_dates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='volatility',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.CreateModel(
            name='StrategyAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('probability_of_profit', models.FloatField()),
                ('strategy_cost', models.FloatField()),
                ('per_leg_cost', models.TextField()),
                ('profit_ranges', models.TextField()),
                ('minimum_return_in_domain', models.FloatField()),
                ('maximum_return_in_domain', models.FloatField()),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='finance_api.strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategyLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('call', 'Call'), ('put', 'Put'), ('stock', 'Stock'), ('closed', 'Closed')], max_length=10)),
                ('strike', models.FloatField(blank=True, null=True)),
                ('premium', models.FloatField(blank=True, null=True)),
                ('n', models.IntegerField()),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('prevpos', models.FloatField()),
                ('expiration', models.CharField(blank=True, max_length=20, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='finance_api.strategy')),
            ],
        ),
        migrations.AddField(
            model_name='strategy',
            name='strategy_legs',
            field=models.ManyToManyField(related_name='strategies', to='finance_api.strategyleg'),
        ),
        migrations.DeleteModel(
            name='FinancialCalculator',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='ProbabilityOfProfit',
        ),
    ]
